image: denoland/deno:1.11.0

stages:
  - test
  - build

test:
  stage: test
  script:
    - deno lint *.ts
    - deno test --unstable --allow-net *.test.ts

build:
  stage: build
  script:
    - deno run --unstable --allow-read --allow-write=dist _build.ts
