image: node:latest

stages:
  - lint
  - test
  - build

before_script:
  - npm ci --cache .npm --prefer-offline
  - export DENO_INSTALL=$PWD/.deno
  - export PATH=$DENO_INSTALL/bin:$PATH
  - [ ! -f $DENO_INSTALL/bin/deno ] && curl -fsSL https://deno.land/x/install/install.sh | sh

cache:
  paths:
    - .npm/
    - .deno/
    - dist/

lint:
  stage: lint
  script: npm run lint

test:
  stage: test
  script: npm test

compile:
  stage: build
  script: npm run build
