image: node:latest

stages:
  - lint
  - test
  - build

before_script:
  - npm ci --cache .npm --prefer-offline
  - export DENO_INSTALL=$PWD/.deno
  - export PATH=$DENO_INSTALL/bin:$PATH
  - if [ -f $DENO_INSTALL/bin/deno ]; then
  - deno upgrade
  - else
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - fi

cache:
  paths:
    - .npm/
    - .deno/
    - dist/

lint:
  stage: lint
  script: npm run lint

test:
  stage: test
  script: npm test

compile:
  stage: build
  script: npm run build
