image: node:latest

stages:
  - build
  - lint
  - test

cache:
  paths:
    - .npm/
    - .server/

setup_cli:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline

setup_server:
  stage: build
  before_script:
    - '[ -d ".server" ] && rm -r .server'
  script:
    - git clone https://gitlab.com/tzstamp/server .server
    - cd .server
    - npm install

lint:
  stage: lint
  script: npm run lint

test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - mv $TESTNET_FAUCET faucet.json
    - mv $CONFIG .env
    - node .server &
    - sleep 20 # wait for server to start
  script:
    - npm test
