image: denoland/deno:1.11.0

stages:
  - test
  - build

test:
  stage: test
  script:
    - deno lint --ignore=node_modules,dist
    - deno test --unstable --allow-net *.test.ts

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install npm -y
    - npm install
  script:
    - deno run --unstable --allow-read=. --allow-write=dist _build.ts
