name: Create Server Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version tag"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_tzstamp_server
        uses: docker/build-push-action@v3
        with:
          context: ./server/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/marigold-dev/tzstamp_server:latest
            ghcr.io/marigold-dev/tzstamp_server:${{ github.event.inputs.version }}
